name: feelingapp
description: Feeling app dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.60+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #flutter_automation: "1.4.0 "
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  preload_page_view: ^0.1.4
  chewie: ^1.0.0
  #flutter_cache_manager: '3.0.1'
  #camera:
  #  git:
  #    url: git://github.com/DealerPeak/plugins.git
  #    path: packages/camera
  #    ref: camera-fix-android-audio
  like_button: ^2.0.4
  camera: ^0.8.1
  firebase_auth: ^1.4.1
  firebase_database: ^7.1.1
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  flutter_tagging: ^3.0.0
  flutter_launcher_icons: "0.9.0"
  flutter_placeholder_textlines: "1.0.4"
  video_thumbnail: ^0.3.3
  image_editor: ^1.0.0
  intl: "0.17.0"
  image_picker: ^0.8.0+3
  progress_indicators: ^1.0.0
  flutter_ffmpeg: ^0.4.0
  convex_bottom_bar: ^3.0.0
  firebase_messaging: ^10.0.2
  geolocator: ^7.1.0
  geoflutterfire: ^3.0.0-nullsafety.4
  email_validator: ^2.0.1
  icon_shadow: "1.0.1"
  expansion_tile_card: ^2.0.0
  cloud_functions: ^1.0.2
  url_launcher: ^6.0.6
  flutter_tags: ^0.4.9+1
  flutter_phoenix: ^1.0.0
  google_sign_in: ^5.0.1
  http: "^0.13.0"
  lottie: "1.0.1"
  share: ^2.0.1
  shared_preferences: ^2.0.6
  location: ^4.2.3
  connectivity: ^3.0.6
  cached_network_image: "3.0.0"
  highlighter_coachmark: "0.0.3"
  flutter_webview_plugin: ^0.4.0
  flutter_local_notifications: ^8.0.0
  apple_sign_in: ^0.1.0
  package_info: ^2.0.2
  firebase_analytics: "8.1.2"
  flutter_facebook_auth: any
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  video_player: ^2.1.12
  intl_phone_field: ^2.1.0
    #dependency_overrides:
    #  video_player:
    #    git:
    #      url: https://github.com/999eagle/plugins.git
    #      ref: feature/caching
    #      path: packages/video_player

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/launcher.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
    - family: DadolIcons
      fonts:
        - asset: assets/icons/DadolIcons.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/rocket.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages