/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DadolIcons {
  DadolIcons._();

  static const _kFontFam = 'DadolIcons';
  static const _inviteFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData x_invite = IconData(0xf135, fontFamily: _inviteFontFam, fontPackage: _kFontPkg);

static const IconData x_upload = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_1x_tap = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_2x_tap = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_3_points = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_arrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_back_arrow = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_birth = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_cancel_dadol = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_check = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_confirm = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_dadol_logo_toolbar = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_distance = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_exclamation_point = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_facebook_logo = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_faq = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_google_logo = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_hashtag = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_insert_hashtag = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_next_arrow = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_play = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_profile = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_rec = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_record_video = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_report_problem = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_scroll = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_search = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_send = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_settings_privacy = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_share = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_smile = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_cross = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_chat = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_dadol_logo_toolbar_center = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
